{% set version = "1.3.0" %}

package:
  name: yasm
  version: {{ version }}

source:
  url: http://www.tortall.net/projects/yasm/releases/yasm-{{ version }}.tar.gz
  sha1: b7574e9f0826bedef975d64d3825f75fbaeef55e
  patches:
    - gh180.patch

build:
  number: 1003

requirements:
  build:
    - {{ compiler('c') }}
    - cmake   # [win]
    - make    # [not win]

test:
  commands:
    - test -f ${PREFIX}/lib/libyasm.a              # [unix]
    - if not exist %LIBRARY_LIB%\\yasm.lib exit 1  # [win]
    - if not exist %LIBRARY_BIN%\\yasm.dll exit 1  # [win]
    - vsyasm --help
    - yasm --help
    - ytasm /h
    - yasm --version

about:
  home: http://www.tortall.net/projects/yasm/
  license: BSD-2-Clause AND BSD-3-Clause AND Artistic-1.0
  license_file:
    - Artistic.txt
    - BSD.txt
  summary: 'Yasm is a complete rewrite of the NASM assembler under the "new" BSD License.'
  dev_url: https://github.com/yasm/yasm

extra:
  recipe-maintainers:
    - jakirkham
    - ocefpaf
    - patricksnape
    - matthiasdiener
